package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;

/**
 *
 * @author joserpp
 */
public class CasillaPanel extends javax.swing.JPanel {

    Casilla casilla;
    
    public CasillaPanel() {
        initComponents();
    }
    
    void setCasilla(Casilla casilla){
    
        this.casilla = casilla;
        
        String nombre = this.casilla.getNombre();
        
        NOMBRE.setText(nombre);
        
        if(!"Salida".equals(nombre)){
            if(!"Sorpresa".equals(nombre)){
                if(!"Parking Público".equals(nombre)){
                    
                    PanelCasillaCalle.setVisible(true);
                    
                    if(((CasillaCalle)this.casilla).tienePropietario()){
                        
                        n_propietario.setText(((CasillaCalle)casilla).getPropietario().getNombre());
                        
                    }
                    else
                        n_propietario.setText("No tiene");
                    
                    p_compra.setText(Float.toString(((CasillaCalle)this.casilla).getPrecioCompra()));
                    p_edificar.setText(Float.toString(((CasillaCalle)this.casilla).getPrecioEdificar()));
                    p_alquiler.setText(Float.toString(((CasillaCalle)this.casilla).getPrecioAlquilerCompleto()));
                }
            }
        }
        else{
        
            /*PROPIETARIO.setVisible(false);
            P_ALQUILER.setVisible(false);
            P_COMPRA.setVisible(false);
            P_EDIFICAR.setVisible(false);*/
            PanelCasillaCalle.setVisible(false);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NOMBRE = new javax.swing.JTextField();
        PanelCasillaCalle = new javax.swing.JPanel();
        PROPIETARIO = new javax.swing.JLabel();
        P_EDIFICAR = new javax.swing.JLabel();
        P_ALQUILER = new javax.swing.JLabel();
        P_COMPRA = new javax.swing.JLabel();
        n_propietario = new javax.swing.JTextField();
        p_compra = new javax.swing.JTextField();
        p_edificar = new javax.swing.JTextField();
        p_alquiler = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        NOMBRE.setBackground(new java.awt.Color(204, 204, 255));
        NOMBRE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        NOMBRE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NOMBRE.setText("jTextField1");
        NOMBRE.setFocusable(false);

        PanelCasillaCalle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PROPIETARIO.setForeground(new java.awt.Color(0, 0, 0));
        PROPIETARIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PROPIETARIO.setText("PROPIETARIO");

        P_EDIFICAR.setForeground(new java.awt.Color(0, 0, 0));
        P_EDIFICAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P_EDIFICAR.setText("PRECIO EDIFICAR");

        P_ALQUILER.setForeground(new java.awt.Color(0, 0, 0));
        P_ALQUILER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P_ALQUILER.setText("PRECIO ALQUILER");

        P_COMPRA.setForeground(new java.awt.Color(0, 0, 0));
        P_COMPRA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P_COMPRA.setText("PRECIO COMPRA");

        n_propietario.setEditable(false);
        n_propietario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n_propietario.setText("jTextField1");

        p_compra.setEditable(false);
        p_compra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_compra.setText("jTextField1");

        p_edificar.setEditable(false);
        p_edificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_edificar.setText("jTextField1");

        p_alquiler.setEditable(false);
        p_alquiler.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p_alquiler.setText("jTextField1");

        javax.swing.GroupLayout PanelCasillaCalleLayout = new javax.swing.GroupLayout(PanelCasillaCalle);
        PanelCasillaCalle.setLayout(PanelCasillaCalleLayout);
        PanelCasillaCalleLayout.setHorizontalGroup(
            PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                                .addComponent(P_EDIFICAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p_edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                                .addComponent(P_ALQUILER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                                .addComponent(P_COMPRA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PROPIETARIO)
                            .addGroup(PanelCasillaCalleLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(n_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCasillaCalleLayout.setVerticalGroup(
            PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCasillaCalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PROPIETARIO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(n_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_COMPRA)
                    .addComponent(p_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_EDIFICAR)
                    .addComponent(p_edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PanelCasillaCalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_ALQUILER)
                    .addComponent(p_alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelCasillaCalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NOMBRE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCasillaCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JLabel PROPIETARIO;
    private javax.swing.JLabel P_ALQUILER;
    private javax.swing.JLabel P_COMPRA;
    private javax.swing.JLabel P_EDIFICAR;
    private javax.swing.JPanel PanelCasillaCalle;
    private javax.swing.JTextField n_propietario;
    private javax.swing.JTextField p_alquiler;
    private javax.swing.JTextField p_compra;
    private javax.swing.JTextField p_edificar;
    // End of variables declaration//GEN-END:variables
}
