package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author joserpp
 */
public class PropiedadPanel extends javax.swing.JPanel {

    CasillaCalle tituloPropiedad;
    
    public void setPropiedad(CasillaCalle tituloPropiedad){
    
        this.tituloPropiedad = tituloPropiedad;
        
        nombre.setText(this.tituloPropiedad.getNombre());
        n_casas.setText(Float.toString(this.tituloPropiedad.getNumCasas()));
        n_hoteles.setText(Float.toString(this.tituloPropiedad.getNumHoteles()));
        
        repaint();
    }
    
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CASAS = new javax.swing.JLabel();
        HOTELES = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        n_casas = new javax.swing.JTextField();
        n_hoteles = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CASAS.setForeground(new java.awt.Color(0, 0, 0));
        CASAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CASAS.setText("CASAS");
        CASAS.setToolTipText("");

        HOTELES.setForeground(new java.awt.Color(0, 0, 0));
        HOTELES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOTELES.setText("HOTELES");
        HOTELES.setToolTipText("");

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(204, 255, 153));
        nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setText("jTextField1");
        nombre.setToolTipText("");
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombre.setFocusable(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        n_casas.setEditable(false);
        n_casas.setForeground(new java.awt.Color(0, 0, 0));
        n_casas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n_casas.setText("jTextField1");
        n_casas.setToolTipText("");

        n_hoteles.setEditable(false);
        n_hoteles.setForeground(new java.awt.Color(0, 0, 0));
        n_hoteles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n_hoteles.setText("jTextField1");
        n_hoteles.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CASAS)
                            .addComponent(HOTELES))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_casas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_hoteles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CASAS)
                    .addComponent(n_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOTELES)
                    .addComponent(n_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CASAS;
    private javax.swing.JLabel HOTELES;
    private javax.swing.JTextField n_casas;
    private javax.swing.JTextField n_hoteles;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
