package GUI;

import civitas.Tablero;
import civitas.Casilla;

/**
 *
 * @author joserpp
 */
public class TableroPanel extends javax.swing.JPanel {

    Tablero tablero;
    
    public TableroPanel() {
        initComponents();
    }
    
    void setTablero(Tablero tablero){
    
        this.tablero = tablero;
        
        SALIDA.setText(this.tablero.getCasilla(0).getNombre());
        CALLE1.setText(this.tablero.getCasilla(1).getNombre());
        CALLE2.setText(this.tablero.getCasilla(2).getNombre());
        SORPRESA1.setText(this.tablero.getCasilla(3).getNombre());
        CALLE3.setText(this.tablero.getCasilla(4).getNombre());
        CALLE4.setText(this.tablero.getCasilla(5).getNombre());
        CALLE5.setText(this.tablero.getCasilla(6).getNombre());
        CALLE6.setText(this.tablero.getCasilla(7).getNombre());
        SORPRESA2.setText(this.tablero.getCasilla(8).getNombre());
        CALLE7.setText(this.tablero.getCasilla(9).getNombre());
        PARKING.setText(this.tablero.getCasilla(10).getNombre());
        CALLE8.setText(this.tablero.getCasilla(11).getNombre());
        CALLE9.setText(this.tablero.getCasilla(12).getNombre());
        SORPRESA3.setText(this.tablero.getCasilla(13).getNombre());
        CALLE10.setText(this.tablero.getCasilla(14).getNombre());
        CALLE11.setText(this.tablero.getCasilla(15).getNombre());
        CALLE12.setText(this.tablero.getCasilla(16).getNombre());
        SORPRESA4.setText(this.tablero.getCasilla(17).getNombre());
        CALLE13.setText(this.tablero.getCasilla(18).getNombre());
        CALLE14.setText(this.tablero.getCasilla(19).getNombre());
    }
    
    void actualizaCasilla(Casilla casilla_actual){
    
        casillaPanel1.setCasilla(casilla_actual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CALLE14 = new javax.swing.JTextField();
        CALLE13 = new javax.swing.JTextField();
        SORPRESA4 = new javax.swing.JTextField();
        CALLE12 = new javax.swing.JTextField();
        CALLE11 = new javax.swing.JTextField();
        CALLE1 = new javax.swing.JTextField();
        SORPRESA1 = new javax.swing.JTextField();
        CALLE3 = new javax.swing.JTextField();
        CALLE2 = new javax.swing.JTextField();
        SORPRESA2 = new javax.swing.JTextField();
        CALLE7 = new javax.swing.JTextField();
        CALLE4 = new javax.swing.JTextField();
        CALLE5 = new javax.swing.JTextField();
        CALLE6 = new javax.swing.JTextField();
        SORPRESA3 = new javax.swing.JTextField();
        CALLE8 = new javax.swing.JTextField();
        PARKING = new javax.swing.JTextField();
        CALLE9 = new javax.swing.JTextField();
        CALLE10 = new javax.swing.JTextField();
        SALIDA = new javax.swing.JTextField();
        casillaPanel1 = new GUI.CasillaPanel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setForeground(new java.awt.Color(0, 0, 0));
        setFocusable(false);

        CALLE14.setBackground(new java.awt.Color(51, 102, 255));
        CALLE14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE14.setForeground(new java.awt.Color(0, 0, 0));
        CALLE14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE14.setText("jTextField1");
        CALLE14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE14.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE14.setFocusable(false);

        CALLE13.setBackground(new java.awt.Color(51, 102, 255));
        CALLE13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE13.setForeground(new java.awt.Color(0, 0, 0));
        CALLE13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE13.setText("jTextField1");
        CALLE13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE13.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE13.setFocusable(false);

        SORPRESA4.setBackground(new java.awt.Color(255, 153, 0));
        SORPRESA4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SORPRESA4.setForeground(new java.awt.Color(0, 0, 0));
        SORPRESA4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SORPRESA4.setText("jTextField1");
        SORPRESA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SORPRESA4.setCaretColor(new java.awt.Color(0, 0, 0));
        SORPRESA4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SORPRESA4.setFocusable(false);

        CALLE12.setBackground(new java.awt.Color(51, 102, 255));
        CALLE12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE12.setForeground(new java.awt.Color(0, 0, 0));
        CALLE12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE12.setText("jTextField1");
        CALLE12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE12.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE12.setFocusable(false);

        CALLE11.setBackground(new java.awt.Color(153, 255, 102));
        CALLE11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE11.setForeground(new java.awt.Color(0, 0, 0));
        CALLE11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE11.setText("jTextField1");
        CALLE11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE11.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE11.setFocusable(false);

        CALLE1.setBackground(new java.awt.Color(255, 51, 51));
        CALLE1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE1.setForeground(new java.awt.Color(0, 0, 0));
        CALLE1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE1.setText("jTextField1");
        CALLE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE1.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE1.setFocusable(false);

        SORPRESA1.setBackground(new java.awt.Color(255, 153, 0));
        SORPRESA1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SORPRESA1.setForeground(new java.awt.Color(0, 0, 0));
        SORPRESA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SORPRESA1.setText("jTextField1");
        SORPRESA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SORPRESA1.setCaretColor(new java.awt.Color(0, 0, 0));
        SORPRESA1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SORPRESA1.setFocusable(false);

        CALLE3.setBackground(new java.awt.Color(255, 51, 51));
        CALLE3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE3.setForeground(new java.awt.Color(0, 0, 0));
        CALLE3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE3.setText("jTextField1");
        CALLE3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE3.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE3.setFocusable(false);

        CALLE2.setBackground(new java.awt.Color(255, 51, 51));
        CALLE2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE2.setForeground(new java.awt.Color(0, 0, 0));
        CALLE2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE2.setText("jTextField1");
        CALLE2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE2.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE2.setFocusable(false);

        SORPRESA2.setBackground(new java.awt.Color(255, 153, 0));
        SORPRESA2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SORPRESA2.setForeground(new java.awt.Color(0, 0, 0));
        SORPRESA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SORPRESA2.setText("jTextField1");
        SORPRESA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SORPRESA2.setCaretColor(new java.awt.Color(0, 0, 0));
        SORPRESA2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SORPRESA2.setFocusable(false);

        CALLE7.setBackground(new java.awt.Color(255, 255, 102));
        CALLE7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE7.setForeground(new java.awt.Color(0, 0, 0));
        CALLE7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE7.setText("jTextField1");
        CALLE7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE7.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE7.setFocusable(false);

        CALLE4.setBackground(new java.awt.Color(255, 51, 51));
        CALLE4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE4.setForeground(new java.awt.Color(0, 0, 0));
        CALLE4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE4.setText("jTextField1");
        CALLE4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE4.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE4.setFocusable(false);
        CALLE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALLE4ActionPerformed(evt);
            }
        });

        CALLE5.setBackground(new java.awt.Color(255, 255, 102));
        CALLE5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE5.setForeground(new java.awt.Color(0, 0, 0));
        CALLE5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE5.setText("jTextField1");
        CALLE5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE5.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE5.setFocusable(false);

        CALLE6.setBackground(new java.awt.Color(255, 255, 102));
        CALLE6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE6.setForeground(new java.awt.Color(0, 0, 0));
        CALLE6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE6.setText("jTextField1");
        CALLE6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE6.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE6.setFocusable(false);
        CALLE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALLE6ActionPerformed(evt);
            }
        });

        SORPRESA3.setBackground(new java.awt.Color(255, 153, 0));
        SORPRESA3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SORPRESA3.setForeground(new java.awt.Color(0, 0, 0));
        SORPRESA3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SORPRESA3.setText("jTextField1");
        SORPRESA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SORPRESA3.setCaretColor(new java.awt.Color(0, 0, 0));
        SORPRESA3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SORPRESA3.setFocusable(false);

        CALLE8.setBackground(new java.awt.Color(153, 255, 102));
        CALLE8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE8.setForeground(new java.awt.Color(0, 0, 0));
        CALLE8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE8.setText("jTextField1");
        CALLE8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE8.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE8.setFocusable(false);

        PARKING.setBackground(new java.awt.Color(255, 204, 255));
        PARKING.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PARKING.setForeground(new java.awt.Color(0, 0, 0));
        PARKING.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PARKING.setText("jTextField1");
        PARKING.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PARKING.setCaretColor(new java.awt.Color(0, 0, 0));
        PARKING.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PARKING.setFocusable(false);

        CALLE9.setBackground(new java.awt.Color(153, 255, 102));
        CALLE9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE9.setForeground(new java.awt.Color(0, 0, 0));
        CALLE9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE9.setText("jTextField1");
        CALLE9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE9.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE9.setFocusable(false);

        CALLE10.setBackground(new java.awt.Color(153, 255, 102));
        CALLE10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CALLE10.setForeground(new java.awt.Color(0, 0, 0));
        CALLE10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CALLE10.setText("jTextField1");
        CALLE10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CALLE10.setCaretColor(new java.awt.Color(0, 0, 0));
        CALLE10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CALLE10.setFocusable(false);

        SALIDA.setBackground(new java.awt.Color(255, 204, 255));
        SALIDA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SALIDA.setForeground(new java.awt.Color(0, 0, 0));
        SALIDA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SALIDA.setText("jTextField1");
        SALIDA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SALIDA.setCaretColor(new java.awt.Color(0, 0, 0));
        SALIDA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SALIDA.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CALLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CALLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SORPRESA3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CALLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CALLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PARKING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SALIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CALLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CALLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SORPRESA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CALLE3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CALLE13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SORPRESA4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CALLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CALLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CALLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SORPRESA2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SALIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SORPRESA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALLE3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CALLE4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CALLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CALLE13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SORPRESA4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SORPRESA2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CALLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CALLE7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CALLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SORPRESA3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PARKING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CALLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CALLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CALLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CALLE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALLE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CALLE4ActionPerformed

    private void CALLE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALLE6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CALLE6ActionPerformed
                    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CALLE1;
    private javax.swing.JTextField CALLE10;
    private javax.swing.JTextField CALLE11;
    private javax.swing.JTextField CALLE12;
    private javax.swing.JTextField CALLE13;
    private javax.swing.JTextField CALLE14;
    private javax.swing.JTextField CALLE2;
    private javax.swing.JTextField CALLE3;
    private javax.swing.JTextField CALLE4;
    private javax.swing.JTextField CALLE5;
    private javax.swing.JTextField CALLE6;
    private javax.swing.JTextField CALLE7;
    private javax.swing.JTextField CALLE8;
    private javax.swing.JTextField CALLE9;
    private javax.swing.JTextField PARKING;
    private javax.swing.JTextField SALIDA;
    private javax.swing.JTextField SORPRESA1;
    private javax.swing.JTextField SORPRESA2;
    private javax.swing.JTextField SORPRESA3;
    private javax.swing.JTextField SORPRESA4;
    private GUI.CasillaPanel casillaPanel1;
    // End of variables declaration//GEN-END:variables
}
